# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/blog.rb.tmpl in the blogtool repo.
class Blog < Formula
  desc "Single-binary static blog tool — posts, ideas, drafts, templates"
  homepage "https://github.com/simonski/blogtool"
  version "0.1.16"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.16/blog_0.1.16_darwin_arm64.tar.gz"
      sha256 "96ea73c48aac26df5ca465c5ac0f9d38d4c447c36ae348190129e7be34a6f2d0"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.16/blog_0.1.16_darwin_amd64.tar.gz"
      sha256 "2cc88817254fd9693c5067998c8e105202b130f8666e3bb5f46599a1b3080b09"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.16/blog_0.1.16_linux_arm64.tar.gz"
      sha256 "19a75e5e19ecc0c9f00af806e84810dbd85270d0748e90c4299fb89167fd65b5"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.16/blog_0.1.16_linux_amd64.tar.gz"
      sha256 "f4e1393ad500c96a5ead5f05841f6330f6b8149c4b1c5b862741a2fe9bce42fa"
    end
  end

  def install
    bin.install "blog"
  end

  test do
    assert_match "0.1.16", shell_output("#{bin}/blog version")
  end
end
