# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/kp.rb.tmpl in the kp repo.
class Kp < Formula
  desc "A terminal tool to manage encrypted key/value pairs"
  homepage "https://github.com/simonski/kp"
  version "0.0.49"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/kp/releases/download/v0.0.49/kp_0.0.49_darwin_arm64.tar.gz"
      sha256 "80cf2be3c23eb98c3a3c8a3e9cba5893b37195e23c87a2ec8d5fba26c3f6c094"
    end

    on_intel do
      url "https://github.com/simonski/kp/releases/download/v0.0.49/kp_0.0.49_darwin_amd64.tar.gz"
      sha256 "8051ea43eeb7d92a63b97dfc76ed3f3ee700ff6e48dbd6a2f53484cc2fa6d98d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/kp/releases/download/v0.0.49/kp_0.0.49_linux_arm64.tar.gz"
      sha256 "ccca664617c55e25ccb078a30df98ffaad71c474fc45c655c67df3fec6a0f86b"
    end

    on_intel do
      url "https://github.com/simonski/kp/releases/download/v0.0.49/kp_0.0.49_linux_amd64.tar.gz"
      sha256 "7ea1a43943a947b435a45d20ae1565994e4195b57ed434d14947f2091b2868bd"
    end
  end

  def install
    bin.install "kp"
  end

  test do
    assert_match "0.0.49", shell_output("#{bin}/kp version")
  end
end
