# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Respec < Formula
  desc "Spec-driven wrapper for agentic programming CLIs"
  homepage "https://github.com/simonski/respec"
  version "0.1.32"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simonski/respec/releases/download/v0.1.32/respec_0.1.32_darwin_amd64.tar.gz"
      sha256 "1bf299b99495fb0f01fd4cedbe0e4ff05abdb9955548bfb24ea4bb06c394e089"

      define_method(:install) do
        bin.install "respec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simonski/respec/releases/download/v0.1.32/respec_0.1.32_darwin_arm64.tar.gz"
      sha256 "8c49a612fa1a6c83a6f11f9aecf64dcab5a8443e7c040f270935eef7ed9331bf"

      define_method(:install) do
        bin.install "respec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/respec/releases/download/v0.1.32/respec_0.1.32_linux_amd64.tar.gz"
      sha256 "93c364be811981bdd3db321dc9451b2f6a476524f60d61731190747f90dd9bb6"
      define_method(:install) do
        bin.install "respec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/respec/releases/download/v0.1.32/respec_0.1.32_linux_arm64.tar.gz"
      sha256 "2e1cefde57812a45eaebb18755c86708faa9a5c4f06e580fa54664b54e012f91"
      define_method(:install) do
        bin.install "respec"
      end
    end
  end

  test do
    system "#{bin}/respec", "help"
  end
end
