# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Spec-driven wrapper for agentic programming CLIs"
  homepage "https://github.com/simonski/sd"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simonski/sd/releases/download/v0.1.5/sd_0.1.5_darwin_amd64.tar.gz"
      sha256 "15855d02bd02209a94b2c36e61b546df0c192ff0790ceeda7d4a5d6fdca5e1cc"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simonski/sd/releases/download/v0.1.5/sd_0.1.5_darwin_arm64.tar.gz"
      sha256 "280460c507e523726f58da0c979ec72b2e64bdf540607246c80f7445d79f5afd"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.5/sd_0.1.5_linux_amd64.tar.gz"
      sha256 "b23f23b031ec61613b5c3a29460f50a3b951c77c5fd8d6792eff27230dbe1310"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.5/sd_0.1.5_linux_arm64.tar.gz"
      sha256 "e958379c83724c5a680ada882d10e82cc1b31a6b3b27ebceb5b5f706c0d070d4"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    system "#{bin}/sd", "help"
  end
end
