# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Spec-driven wrapper for agentic programming CLIs"
  homepage "https://github.com/simonski/sd"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simonski/sd/releases/download/v0.1.6/sd_0.1.6_darwin_amd64.tar.gz"
      sha256 "3f6aa6be9b8fc3f4d573d8a5b5eb644a9773df862beb36f344d2d26cc761bd44"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simonski/sd/releases/download/v0.1.6/sd_0.1.6_darwin_arm64.tar.gz"
      sha256 "0ead67a43aad28a5e3d7b4a34405c3975d747ea025710ccf3c8dfd3520029006"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.6/sd_0.1.6_linux_amd64.tar.gz"
      sha256 "2d9273de061b3505a7b23309f3d4fafcac67a6a1bc3c32e6b357f4994ebd07fe"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.6/sd_0.1.6_linux_arm64.tar.gz"
      sha256 "5a26beb7dd2f26665270703f877b9142710a393fcd87a85850f9b1769719be79"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    system "#{bin}/sd", "help"
  end
end
