# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Spec-driven wrapper for agentic programming CLIs"
  homepage "https://github.com/simonski/sd"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simonski/sd/releases/download/v0.1.9/sd_0.1.9_darwin_amd64.tar.gz"
      sha256 "b5148c2468eb45ab2432bcaba31326b8b2993b3ab9a680e6c64e9cdc433c57f6"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simonski/sd/releases/download/v0.1.9/sd_0.1.9_darwin_arm64.tar.gz"
      sha256 "c71d6626a6b6920d6135add0dcdc191bed06007c2979763d711894bd190f5a12"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.9/sd_0.1.9_linux_amd64.tar.gz"
      sha256 "c35e88fce03f3d1f88227dd930e78178914e4210f3841d6667514c26bd629935"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonski/sd/releases/download/v0.1.9/sd_0.1.9_linux_arm64.tar.gz"
      sha256 "1ba6d1549442e14716855d306db1b18b5bd9cf1564c5a78948e9a3c5491d985d"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    system "#{bin}/sd", "help"
  end
end
