# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.586"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.586/ticket_0.1.586_darwin_arm64.tar.gz"
      sha256 "7c02f6c5b6f87c415f4d22b534bb6f0a8b2c30491eca129d39d20fae1e7caf2b"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.586/ticket_0.1.586_darwin_amd64.tar.gz"
      sha256 "f29efec222b50d4bf65c66363430b141ec0e09c87fa9d234b44da91b677a1fe6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.586/ticket_0.1.586_linux_arm64.tar.gz"
      sha256 "83f8a53476a60e586dc49c3d52205ab4d7d3623ed7c0096883c6ae67ad001db1"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.586/ticket_0.1.586_linux_amd64.tar.gz"
      sha256 "f0a03bcd7f20103839a63d1c37b03fbf53b7cbbbb66fe22053a155a3830af943"
    end
  end

  def install
    bin.install "ticket"
    # Also expose as `tk` for the short-form CLI
    bin.install_symlink bin/"ticket" => "tk"
  end

  test do
    assert_match "0.1.586", shell_output("#{bin}/ticket version")
  end
end
