# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.1091"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/v0.1.1091/tk_0.1.1091_darwin_arm64.tar.gz"
      sha256 "3da672107db24a803b2d4fbe56709f28886245dcdffd28cf4dc2481698433fc0"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/v0.1.1091/tk_0.1.1091_darwin_amd64.tar.gz"
      sha256 "0b5f773dd9eb127a65b970fba9cdb5cbae17085bed0baddc2775cb1440a1a940"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/v0.1.1091/tk_0.1.1091_linux_arm64.tar.gz"
      sha256 "0775c94a8ff8cc0cdd8377b861cbfc97e32fe4c1759ae8c612841f91ac2af336"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/v0.1.1091/tk_0.1.1091_linux_amd64.tar.gz"
      sha256 "698590e6df880ac3e3d72666e7e01eb21a27f3b8bffa0fe030f8efe6585ab21e"
    end
  end

  def install
    bin.install "tk"
  end

  test do
    assert_match "0.1.1091", shell_output("#{bin}/tk version")
  end
end
