# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.954"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_arm64.tar.gz"
      sha256 ""
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_amd64.tar.gz"
      sha256 ""
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_arm64.tar.gz"
      sha256 ""
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_amd64.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "tk"
  end

  test do
    assert_match "0.1.954", shell_output("#{bin}/tk version")
  end
end
